name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rustfmt:
    name: Check rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: nightly
          components: rustfmt

      - name: Check rust code formatting
        run: cargo fmt --check

  clippy:
    name: Check clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          components: clippy

      - name: Check clippy warnings
        run: cargo clippy --all-targets --all-features --benches --lib --tests -- -D warnings

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable

      - name: Run tests
        run: cargo test --all-targets --all-features
